# Generated by Django 5.2 on 2025-05-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')])),
                ('position', models.CharField(choices=[('GM', 'Manager'), ('AGM', 'AssistantGeneralManager'), ('BARTENDER', 'Bartender'), ('WAITER', 'Waiter'), ('SUPERVISOR', 'Supervisor'), ('BARBACK', 'BarBack')])),
                ('user_code', models.IntegerField(max_length=4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('last_sign_in', models.DateTimeField()),
                ('last_sign_out', models.DateTimeField()),
                ('isOnBreak', models.BooleanField(default=False)),
            ],
        ),
    ]
