# Generated by Django 5.2 on 2025-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_code',
            field=models.IntegerField(unique=True),
        ),
    ]
