# Generated by Django 5.2 on 2025-05-09 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_app', '0002_alter_employee_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isOnShift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GM', 'Manager'), ('AGM', 'AssistantGeneralManager'), ('BARTENDER', 'Bartender'), ('WAITER', 'Waiter'), ('SUPERVISOR', 'Supervisor'), ('BARBACK', 'BarBack')], max_length=10),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(choices=[('START_SHIFT', 'Start my shift'), ('FINISH_SHIFT', 'Finish my shift'), ('START_BREAK', 'Start my break'), ('FINISH_BREAK', 'Finish my break')])),
                ('photo', models.ImageField(upload_to='snapshots/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sign_in_app.employee')),
            ],
        ),
    ]
