# Generated by Django 5.2 on 2025-05-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_app', '0003_employee_isonshift_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_sign_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_sign_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
