# Generated by Django 5.2 on 2025-05-11 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_app', '0004_alter_employee_last_sign_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
